name: azure_ad_authentication
description: The Microsoft Authentication Library (MSAL) enables developers to acquire tokens
  from the Microsoft identity platform in order to authenticate users and access secured
version: 1.0.2

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: '>=3.3.2'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  msal_js: ^2.14.0

  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.fmi.azure_ad_authentication
        pluginClass: AzureAdAuthenticationPlugin
      ios:
        pluginClass: AzureAdAuthenticationPlugin
      web:
        pluginClass: AzureAdAuthenticationPlugin
        fileName: azure_ad_auth_web.dart