// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'content_source_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ContentSourceModel _$ContentSourceModelFromJson(Map<String, dynamic> json) =>
    ContentSourceModel(
      content: json['content'] as String,
      platform: json['platform'] as String?,
      component: $enumDecodeNullable(_$DemosEnumMap, json['component']),
      componentName: json['componentName'] as String?,
    );

Map<String, dynamic> _$ContentSourceModelToJson(ContentSourceModel instance) =>
    <String, dynamic>{
      'content': instance.content,
      'platform': instance.platform,
      'componentName': instance.componentName,
      'component': _$DemosEnumMap[instance.component],
    };

const _$DemosEnumMap = {
  Demos.fmiCardHeaderListTile: 'fmiCardHeaderListTile',
  Demos.subtitleTwoLine: 'subtitleTwoLine',
  Demos.titleListTiles: 'titleListTiles',
  Demos.titleWithOverline: 'titleWithOverline',
  Demos.titleWithSubscript: 'titleWithSubscript',
  Demos.fmiMineOverview: 'fmiMineOverview',
  Demos.fmiMaterialOverview: 'fmiMaterialOverview',
  Demos.fmiWarningTextField: 'fmiWarningTextField',
  Demos.fmiToggleButton: 'fmiToggleButton',
  Demos.fmiTimeline: 'fmiTimeline',
  Demos.fmiSignatureCanvas: 'fmiSignatureCanvas',
  Demos.fmiSignatureDialog: 'fmiSignatureDialog',
  Demos.fmiSignatureViewer: 'fmiSignatureViewer',
  Demos.fmiScorecard: 'fmiScorecard',
  Demos.fmiAttachment: 'fmiAttachment',
  Demos.photoAttachment: 'photoAttachment',
  Demos.fmiPhoneNumberInput: 'fmiPhoneNumberInput',
  Demos.fmiMultiSelectList: 'fmiMultiSelectList',
  Demos.fmiMultiInput: 'fmiMultiInput',
  Demos.fmiMultiDialogIconButton: 'fmiMultiDialogIconButton',
  Demos.employeeLookup: 'employeeLookup',
  Demos.fmiDialogIconButton: 'fmiDialogIconButton',
  Demos.fmiConnectedAssetLookup: 'fmiConnectedAssetLookup',
  Demos.conditionalQuestion: 'conditionalQuestion',
  Demos.radioButtonGroup: 'radioButtonGroup',
  Demos.fmiAvatar: 'fmiAvatar',
  Demos.errorCardHeader: 'errorCardHeader',
  Demos.fmiBadge: 'fmiBadge',
  Demos.slidingVisibility: 'slidingVisibility',
  Demos.fmiIconButton: 'fmiIconButton',
  Demos.fmiMultiEmployeeLookup: 'fmiMultiEmployeeLookup',
  Demos.closeableAppBar: 'closeableAppBar',
  Demos.fmiKpiCard: 'fmiKpiCard',
  Demos.fmiKpiGraphCard: 'fmiKpiGraphCard',
  Demos.fmiMultiSelect: 'fmiMultiSelect',
  Demos.fmiNavigationRail: 'fmiNavigationRail',
  Demos.fmiBottomNavigationBar: 'fmiBottomNavigationBar',
  Demos.fmiExpandableKpiCard: 'fmiExpandableKpiCard',
  Demos.fmiAppBarTop: 'fmiAppBarTop',
  Demos.fmiTabBar: 'fmiTabBar',
  Demos.fmiNaWarningTextField: 'fmiNaWarningTextField',
  Demos.fmiMultiSelectFilter: 'fmiMultiSelectFilter',
  Demos.fmiSingleSelectFilter: 'fmiSingleSelectFilter',
  Demos.fmiHoverCard: 'fmiHoverCard',
  Demos.fmiSearchSingleSelect: 'fmiSearchSingleSelect',
  Demos.fmiGenericCard: 'fmiGenericCard',
  Demos.fmiProgressBar: 'fmiProgressBar',
  Demos.fmiHyperlink: 'fmiHyperlink',
  Demos.fmiMap: 'fmiMap',
  Demos.fmiLocationPicker: 'fmiLocationPicker',
  Demos.fmiCandyBar: 'fmiCandyBar',
  Demos.genericLookup: 'genericLookup',
  Demos.colors: 'colors',
  Demos.typography: 'typography',
  Demos.mediaGraphics: 'mediaGraphics',
  Demos.spacingLayout: 'spacingLayout',
  Demos.iconography: 'iconography',
  Demos.snackBarService: 'snackBarService',
  Demos.fmiEmployeeInfoWidget: 'fmiEmployeeInfoWidget',
  Demos.elevatedButton: 'elevatedButton',
  Demos.textButton: 'textButton',
  Demos.outlinedButton: 'outlinedButton',
  Demos.dropdownButton: 'dropdownButton',
  Demos.filledButton: 'filledButton',
  Demos.fabDefault: 'fabDefault',
  Demos.fabPrimary: 'fabPrimary',
  Demos.fabPrimaryContainer: 'fabPrimaryContainer',
  Demos.fabSecondary: 'fabSecondary',
  Demos.fabSecondaryContainer: 'fabSecondaryContainer',
  Demos.fabTertiary: 'fabTertiary',
  Demos.fabTertiaryContainer: 'fabTertiaryContainer',
  Demos.fabHero: 'fabHero',
  Demos.fabZeroElevation: 'fabZeroElevation',
  Demos.fmiEmployeeDirectorySearch: 'fmiEmployeeDirectorySearch',
  Demos.fmiOverviewBar: 'fmiOverviewBar',
  Demos.bottomSheet: 'bottomSheet',
  Demos.fmiSearchDialog: 'fmiSearchDialog',
  Demos.cardThemeDefault: 'cardThemeDefault',
  Demos.cardThemeElevated: 'cardThemeElevated',
  Demos.cardThemeFilled: 'cardThemeFilled',
  Demos.cardThemeOutline: 'cardThemeOutline',
  Demos.cardThemeSecondary: 'cardThemeSecondary',
  Demos.appBarThemes: 'appBarThemes',
  Demos.fmiNavigationDrawer: 'fmiNavigationDrawer',
  Demos.datePickerDefault: 'datePickerDefault',
  Demos.timePickerDefault: 'timePickerDefault',
  Demos.genericLookupMultiSelect: 'genericLookupMultiSelect',
  Demos.dateRangePickerDefault: 'dateRangePickerDefault',
  Demos.dropdownButtonFormField: 'dropdownButtonFormField',
  Demos.fmiCarouselWidget: 'fmiCarouselWidget',
  Demos.treeview: 'treeview',
  Demos.oobSegmentedButton: 'oobSegmentedButton',
  Demos.defaultBarChart: 'defaultBarChart',
  Demos.defaultLineChart: 'defaultLineChart',
  Demos.defaultPieChart: 'defaultPieChart',
  Demos.dataGrid: 'dataGrid',
  Demos.defaultBottomNavBar: 'defaultBottomNavBar',
  Demos.textField: 'textField',
  Demos.actionChips: 'actionChips',
  Demos.choiceChips: 'choiceChips',
  Demos.filterChips: 'filterChips',
  Demos.inputChips: 'inputChips',
  Demos.fmiAppBar: 'fmiAppBar',
};
