name: ideation_widgetbook
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ideation:
    path: ../
  widgetbook: ^3.10.0
  widgetbook_annotation: ^3.0.0
  device_frame: ^1.1.0
  fmi_core:
    path: ../MDS/packages/fmi_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  widgetbook_generator: ^3.9.0
  build_runner: ^2.4.11

dependency_overrides:
  ffi: ^2.0.1
  http: ^1.0.0

flutter:
  uses-material-design: true
