name: Flutter POC

trigger: [main]

variables:
  FlutterVersion: '3.3.2'

stages:
- stage: ci
  displayName: Continuous Integration
  jobs:
  - job: web
    displayName: Build Flutter POC web app
    pool:
      vmImage: windows-latest
    steps:
    - task: FlutterInstall@0
      displayName: Install Flutter SDK
      inputs:
        version: custom
        customVersion: $(FlutterVersion)
    - task: FlutterBuild@0
      displayName: Build the web application
      inputs:
        target: web
    - publish: build/web
      artifact: Web
      displayName: Publish web application
  - job: android
    displayName: Build Flutter POC Android app
    pool:
      vmImage: macOS-latest
    steps:
    - task: FlutterInstall@0
      displayName: Install Flutter SDK
      inputs:
        version: custom
        customVersion: $(FlutterVersion)
    - task: DownloadSecureFile@1
      name: keystore
      displayName: Download keystore.jks
      inputs:
        secureFile: 'keystore.jks'
    - task: DownloadSecureFile@1
      name: keyProperties
      displayName: Download key.properties
      inputs:
        secureFile: 'key.properties'
    - script: |
        cp $(keystore.secureFilePath) android/app/keystore.jks
        cp $(keyProperties.secureFilePath) android/key.properties
    - task: FlutterBuild@0
      displayName: Build the Android APK
      inputs:
        target: apk
        splitPerAbi: true
    - task: FlutterBuild@0
      displayName: Build the Android app bundle
      inputs:
        target: aab
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: build/app/outputs/apk/release
        artifactName: APK
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: build/app/outputs/bundle/release/app-release.aab
        artifactName: AAB
