name: poc
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=3.3.2"

dependency_overrides:
  ffi: ^2.0.1
  http: 1.0.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # The following adds provider patter for essential application state management patters
  provider: ^6.0.0

  # MVVM / state management
  stacked:

    # dependency injection
  get_it: ^7.2.0

  # markdown viewer package
  flutter_markdown: ^0.6.10
  url_launcher: ^6.1.5
  json_annotation:
  clipboard: ^0.1.3

  # path provider
  path_provider: ^2.0.10

  fmi_core:
    path: packages/fmi_core

  isar: 2.4.0
  isar_flutter_libs: 2.4.0

  # The following adds font awesome to be utilized in icon
  font_awesome_flutter:
    path: ./packages/fmi-mineral-dsp/dist/font_awesome_flutter

  flutter_svg:
  intl_phone_number_input: ^0.7.1
  mobile_scanner: ^3.5.5
  skeleton_loader: ^2.0.0+4
  scrollable_positioned_list: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

  # json_serializable
  json_serializable:

  build_runner:

  # isar database generators
  isar_generator:
    path: ./packages/fmi_core/packages/isar_generator

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/content/page_manifest.json
    - lib/assets/content/components/components_overview.md
    - lib/assets/content/components/animation/sliding_visibility/
    - lib/assets/content/components/attachment/fmiAttachment/
    - lib/assets/content/components/attachment/photoAttachment/
    - lib/assets/content/components/bar/appBarTop/
    - lib/assets/content/components/bar/appBarTop/
    - lib/assets/content/components/badges/
    - lib/assets/content/components/bottomSheet/
    - lib/assets/content/components/button/fmi_core/
    - lib/assets/content/components/button/fmi_core/dialogIconButton/
    - lib/assets/content/components/button/fmi_core/toggleButton/
    - lib/assets/content/components/button/fmi_core/iconButton/
    - lib/assets/content/components/button/fmi_core/multiDialogIconButton/
    - lib/assets/content/components/button/oob/
    - lib/assets/content/components/button/oob/elevatedButton/
    - lib/assets/content/components/button/oob/outlinedButton/
    - lib/assets/content/components/button/oob/textButton/
    - lib/assets/content/components/button/oob/floatingActionButton/
    - lib/assets/content/components/button/oob/filledButton/
    - lib/assets/content/components/button/oob/dropdownButton/
    - lib/assets/content/components/button/oob/dropdownButtonFormField/
    - lib/assets/content/components/button/oob/segmentedButton/
    - lib/assets/content/components/button/oob/floatingActionButton/
    - lib/assets/content/components/radio/radioButton/radioButton_design.md
    - lib/assets/content/components/radio/radioButton/radioButton_flutter.md
    - lib/assets/content/components/candyBar/fmi_candy_bar_design.md
    - lib/assets/content/components/candyBar/fmi_candy_bar_flutter.md
    - lib/assets/content/components/cards/errorHeaderCard/
    - lib/assets/content/components/cards/fmiExpandableKpiCard/
    - lib/assets/content/components/cards/fmiGenericCard/
    - lib/assets/content/components/cards/fmiKpiGraphCard/
    - lib/assets/content/components/cards/fmiKpiListCard/
    - lib/assets/content/components/cards/fmiMaterialOverview/
    - lib/assets/content/components/cards/fmiMineOverview/
    - lib/assets/content/components/cards/fmiScorecard/
    - lib/assets/content/components/cardThemes/
    - lib/assets/content/components/carousel/
    - lib/assets/content/components/bar/closeable_app_bar/closeable_app_bar_design.md
    - lib/assets/content/components/bar/closeable_app_bar/closeable_app_bar_flutter.md
    - lib/assets/content/components/sampleCharts/dataGrid/dataGrid_design.md
    - lib/assets/content/components/sampleCharts/dataGrid/dataGrid_flutter.md
    - lib/assets/content/components/listTiles/listTilesGuide/listTiles_design.md
    - lib/assets/content/components/listTiles/listTilesGuide/listTiles_flutter.md
    - lib/assets/content/components/listTiles/subtitleTwoLine/subtitleTwoLine_design.md
    - lib/assets/content/components/listTiles/subtitleTwoLine/subtitleTwoLine_flutter.md
    - lib/assets/content/components/listTiles/titleWithSubscript/titleWithSubscript_design.md
    - lib/assets/content/components/listTiles/titleWithSubscript/titleWithSubscript_flutter.md
    - lib/assets/content/components/listTiles/titleListTiles/titleListTiles_design.md
    - lib/assets/content/components/listTiles/titleListTiles/titleListTiles_flutter.md
    - lib/assets/content/components/images/imageIconOverlay/imageIconOverlay_design.md
    - lib/assets/content/components/images/imageIconOverlay/imageIconOverlay_flutter.md
    - lib/assets/content/components/image_slots/image_slot_design.md
    - lib/assets/content/components/image_slots/image_slot_flutter.md
    - lib/assets/content/components/avatar/avatarContent/avatar_design.md
    - lib/assets/content/components/avatar/avatarContent/avatar_flutter.md
    - lib/assets/content/components/employee/fmi_employee_info_widget/
    - lib/assets/content/components/employee/fmi_employee_directory_search/
    - lib/assets/content/components/employee/employee_lookup/
    - lib/assets/content/components/employee/fmi_multi_employee_lookup/
    - lib/assets/content/components/connectedAsset/connected_asset_lookup/connected_asset_lookup_design.md
    - lib/assets/content/components/connectedAsset/connected_asset_lookup/connected_asset_lookup_flutter.md
    - lib/assets/content/components/question/conditionalQuestion/conditionalQuestion_design.md
    - lib/assets/content/components/question/conditionalQuestion/conditionalQuestion_flutter.md
    - lib/assets/content/components/warning/warning_text_field_design.md
    - lib/assets/content/components/warning/warning_text_field_flutter.md
    - lib/assets/content/components/lists/multi_select/multi_select_list_design.md
    - lib/assets/content/components/lists/multi_select/multi_select_list_flutter.md
    - lib/assets/content/components/input/multiInput/multiInput_design.md
    - lib/assets/content/components/input/multiInput/multiInput_flutter.md
    - lib/assets/content/components/multiSelect/fmi_multi_select_design.md
    - lib/assets/content/components/multiSelect/fmi_multi_select_flutter.md
    - lib/assets/content/components/input/phoneNumberInput/phone_number_input_design.md
    - lib/assets/content/components/input/phoneNumberInput/phone_number_input_flutter.md
    - lib/assets/content/components/sampleCharts/defaultBarChart/defaultBarChart_flutter.md
    - lib/assets/content/components/sampleCharts/defaultBarChart/defaultBarChart_design.md
    - lib/assets/content/components/sampleCharts/defaultLineChart/defaultLineChart_flutter.md
    - lib/assets/content/components/sampleCharts/defaultLineChart/defaultLineChart_design.md
    - lib/assets/content/components/sampleCharts/defaultPieChart/defaultPieChart_flutter.md
    - lib/assets/content/components/sampleCharts/defaultPieChart/defaultPieChart_design.md
    - lib/assets/content/components/listTiles/fmiCardHeaderListTile/fmiCardHeaderListTile_design.md
    - lib/assets/content/components/listTiles/fmiCardHeaderListTile/fmiCardHeaderListTile_flutter.md
    - lib/assets/content/components/listTiles/titleWithOverline/titleWithOverline_design.md
    - lib/assets/content/components/listTiles/titleWithOverline/titleWithOverline_flutter.md
    - lib/assets/content/components/timeline/timeline_design.md
    - lib/assets/content/components/timeline/timeline_flutter.md
    - lib/assets/content/components/treeview/treeview_design.md
    - lib/assets/content/components/treeview/treeview_flutter.md
    - lib/assets/content/components/signature/signature_canvas/signature_canvas_design.md
    - lib/assets/content/components/signature/signature_canvas/signature_canvas_flutter.md
    - lib/assets/content/components/signature/signature_dialog/signature_dialog_design.md
    - lib/assets/content/components/signature/signature_dialog/signature_dialog_flutter.md
    - lib/assets/content/components/signature/signature_viewer/signature_viewer_design.md
    - lib/assets/content/components/signature/signature_viewer/signature_viewer_flutter.md
    - lib/assets/content/components/bar/tabBar/tab_bar_design.md
    - lib/assets/content/components/bar/tabBar/tab_bar_flutter.md
    - lib/assets/content/components/navigation/appBarThemes/
    - lib/assets/content/components/navigationDrawer/navigation_drawer_design.md
    - lib/assets/content/components/navigationDrawer/navigation_drawer_flutter.md
    - lib/assets/content/components/navigationRail/navigation_rail_design.md
    - lib/assets/content/components/navigationRail/navigation_rail_flutter.md
    - lib/assets/content/components/naWarning/na_warning_text_field_design.md
    - lib/assets/content/components/naWarning/na_warning_text_field_flutter.md
    - lib/assets/content/components/bottomNavigationBar/fmi_core/fmi_bottom_navigation_bar_design.md
    - lib/assets/content/components/bottomNavigationBar/fmi_core/fmi_bottom_navigation_bar_flutter.md
    - lib/assets/content/components/bottomNavigationBar/oob/default_bottom_navigation_bar_design.md
    - lib/assets/content/components/bottomNavigationBar/oob/default_bottom_navigation_bar_flutter.md
    - lib/assets/content/components/scaffold/scaffold_flutter.md
    - lib/assets/content/components/scaffold/scaffold_design.md
    - lib/assets/content/components/filters/fmiMultiSelectFilter/multi_select_filter_design.md
    - lib/assets/content/components/filters/fmiMultiSelectFilter/multi_select_filter_flutter.md
    - lib/assets/content/components/filters/fmiSingleSelectFilter/single_select_filter_design.md
    - lib/assets/content/components/filters/fmiSingleSelectFilter/single_select_filter_flutter.md
    - lib/assets/content/components/search/single_select/search_single_select_design.md
    - lib/assets/content/components/search/single_select/search_single_select_flutter.md
    - lib/assets/content/components/search/dialog/search_dialog_design.md
    - lib/assets/content/components/search/dialog/search_dialog_flutter.md
    - lib/assets/content/components/snackBar/snackBarService/snack_bar_service_design.md
    - lib/assets/content/components/snackBar/snackBarService/snack_bar_service_flutter.md
    - lib/assets/content/components/syncFusion/fmi_progress_bar_design.md
    - lib/assets/content/components/syncFusion/fmi_progress_bar_flutter.md
    - lib/assets/content/components/hyperlink/hyperlink_design.md
    - lib/assets/content/components/hyperlink/hyperlink_flutter.md
    - lib/assets/content/components/map/mapGuide/fmi_map_design.md
    - lib/assets/content/components/map/mapGuide/fmi_map_flutter.md
    - lib/assets/content/components/locationPicker/fmi_location_picker_design.md
    - lib/assets/content/components/locationPicker/fmi_location_picker_flutter.md
    - lib/assets/content/components/genericLookup/generic_lookup_design.md
    - lib/assets/content/components/genericLookup/generic_lookup_flutter.md
    - lib/assets/content/components/genericLookup/multiSelect/generic_lookup_multi_select_design.md
    - lib/assets/content/components/genericLookup/multiSelect/generic_lookup_multi_select_flutter.md
    - lib/assets/content/components/datetime/datetimePickers/date/
    - lib/assets/content/components/datetime/datetimePickers/time/
    - lib/assets/content/components/datetime/datetimePickers/dateRange/
    - lib/assets/content/components/textField/oob/
    - lib/assets/content/components/chips/actionChip/
    - lib/assets/content/components/chips/choiceChip/
    - lib/assets/content/components/chips/filterChip/
    - lib/assets/content/components/chips/inputChip/
    - lib/assets/content/foundations/colors/colors_design.md
    - lib/assets/content/foundations/typography/typography_design.md
    - lib/assets/content/foundations/typography/typography_flutter.md
    - lib/assets/content/foundations/iconography/iconography_design.md
    - lib/assets/content/foundations/iconography/iconography_flutter.md
    - lib/assets/content/foundations/spacing/spacing_design.md
    - lib/assets/content/foundations/spacing/spacing_flutter.md
    - lib/assets/content/foundations/logos-images/logos-images_design.md
    - lib/assets/content/foundations/logos-images/logos-images_flutter.md
    - lib/assets/content/processes/addingNewComponent/adding_new_component.md
    - lib/assets/content/processes/designTokens/figmaTokens.md
    - lib/assets/content/processes/designTokens/figmaTokens_addingUpdating.md
    - lib/assets/content/demos/demos_overview.md
    - assets/images/animation/
    - assets/images/dashboard-card-demo-images/
    - assets/images/placeholder/
    - assets/images/misc-svgs/
    - assets/images/foundation/
    - assets/images/
    - README.md
    - lib/assets/content/about/about_overview.md
    - packages/fmi_core/README.md
    - packages/fmi-mineral-dsp/README.md
    - lib/assets/content/components/cardSubComponent/fmiOverviewBar/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: lib/fonts/Schyler-Regular.ttf
  #       - asset: lib/fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: lib/fonts/TrajanPro.ttf
  #       - asset: lib/fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: SF Pro Text
      fonts:
        - asset: lib/fonts/SF-Pro-Text-Light.otf
          weight: 300
          style: normal
        - asset: lib/fonts/SF-Pro-Text-LightItalic.otf
          weight: 300
          style: italic
        - asset: lib/fonts/SF-Pro-Text-Regular.otf
          weight: 400
          style: normal
        - asset: lib/fonts/SF-Pro-Text-RegularItalic.otf
          weight: 400
          style: italic
        - asset: lib/fonts/SF-Pro-Text-Medium.otf
          weight: 500
          style: normal
        - asset: lib/fonts/SF-Pro-Text-MediumItalic.otf
          weight: 500
          style: italic
        - asset: lib/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
          style: normal
        - asset: lib/fonts/SF-Pro-Text-Bold.otf
          weight: 700
          style: normal
        - asset: lib/fonts/SF-Pro-Text-BoldItalic.otf
          weight: 700
          style: italic
