enum AssignedView {
  aboutView,
  foundationView,
  componentView,
  processView,
  documentationView,
  landingView,
  demoView,
  demoFlutterView,
  demoColorView,
  demoIllustrationView,
  demoChartView,
  demoDataGridView,
  demoScaffoldView,
  changelogView,
}
