enum FmiColor {
  illustrationsOnBackgroundPurple,
  illustrationsBackgroundPurple,
  illustrationsOnBackgroundRed,
  illustrationsBackgroundRed,
  illustrationsOnBackgroundOrange,
  illustrationsBackgroundOrange,
  illustrationsOnBackgroundGreen,
  illustrationsBackgroundGreen,
  illustrationsOnBackgroundBlue,
  illustrationsBackgroundBlue,
  illustrationsOnBackgroundDarkBlue,
  illustrationsBackgroundDarkBlue,
  illustrationsBackgroundGray,
}